# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_auto_20170322_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='annotation',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\x90\xd0\xbd\xd0\xbd\xd0\xbe\xd1\x82\xd0\xb0\xd1\x86\xd0\xb8\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='film',
            name='artists',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb5\xd1\x80\xd1\x8b'),
        ),
        migrations.AlterField(
            model_name='film',
            name='country',
            field=models.TextField(verbose_name=b'\xd0\xa1\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='film',
            name='cycle',
            field=models.CharField(max_length=100, verbose_name=b'\xd0\xa6\xd0\xb8\xd0\xba\xd0\xbb'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.Genre', verbose_name=b'\xd0\x96\xd0\xb0\xd0\xbd\xd1\x80'),
        ),
        migrations.AlterField(
            model_name='film',
            name='language',
            field=models.TextField(blank=True, null=True, verbose_name=b'\xd0\xaf\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(db_index=True, max_length=60, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='film',
            name='orig_name',
            field=models.CharField(max_length=60, verbose_name=b'\xd0\x9e\xd1\x80\xd0\xb8\xd0\xb3\xd0\xb8\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd0\xbe\xd0\xb5 \xd0\xbd\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.ImageField(blank=True, upload_to=b'uploads/', verbose_name=b'\xd0\x9f\xd0\xbb\xd0\xb0\xd1\x88\xd0\xba\xd0\xb0'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.CharField(max_length=100, verbose_name=b'\xd0\xa0\xd0\xb5\xd0\xb6\xd0\xb8\xd1\x81\xd1\x81\xd0\xb5\xd1\x80'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tagline',
            field=models.CharField(max_length=100, verbose_name=b'\xd0\xa1\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb0\xd0\xbd'),
        ),
        migrations.AlterField(
            model_name='film',
            name='time',
            field=models.CharField(max_length=8, verbose_name=b'\xd0\x92\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(db_index=True, max_length=20, verbose_name=b'\xd0\x93\xd0\xbe\xd0\xb4'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
    ]
